name: Test

on:
  push:

jobs:
  tests:
  

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMin
        run: mvn clean test -Dtest=org.example.MainTest#testForMin

      - name: TestMax
        run: mvn clean test -Dtest=org.example.MainTest#testForMax

      - name: TestSum
        run: mvn clean test -Dtest=org.example.MainTest#testForSum

      - name: TestMult
        run: mvn clean test -Dtest=org.example.MainTest#testForMult
      - name: View_TLG
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Всё ок"
  testingMin:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven

      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: TestMax
        run: mvn clean test -Dtest=org.example.MainTest#testForMax

      - name: CheckMax
        if: failure()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: "Тест на поиск максимума не пройден."

