name: ManualTests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Какой тест пожелаете?
        required: true
        type: choice
        options:
          - min
          - max
          - sum
          - mult


jobs:
  testing:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 21.0.2
        uses: actions/setup-java@v1
        with:
          java-version: '21.0.2'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Test min
        if: "github.event.inputs.deployment_target == 'min'"
        run: mvn clean test -Dtest=org.example.MainTest#testForMin
      - name: Test max
        if: "github.event.inputs.deployment_target == 'max'"
        run: mvn clean test -Dtest=org.example.MainTest#testForMax
      - name: Test sum
        if: "github.event.inputs.deployment_target == 'sum'"
        run: mvn clean test -Dtest=org.example.MainTest#testForSum
      - name: Test mult
        if: "github.event.inputs.deployment_target == 'mult'"
        run: mvn clean test -Dtest=org.example.MainTest#testForMult
